// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRgZOXoE4olEIqx7-BLPsRXgXkeJSq9KE',
    appId: '1:932555800316:web:5e47352bc20ee05e886179',
    messagingSenderId: '932555800316',
    projectId: 'firebase-all-features',
    authDomain: 'fir-all-features-dd471.firebaseapp.com',
    databaseURL: 'https://firebase-all-features-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firebase-all-features.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaDsmqzDRtJ-k0MXj42vICGV085aCsdf0',
    appId: '1:932555800316:android:2daf4a84729c8a51886179',
    messagingSenderId: '932555800316',
    projectId: 'firebase-all-features',
    databaseURL: 'https://firebase-all-features-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firebase-all-features.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdKsSmB3dbcrkN5yQi1uJNGtnyn9Egxh8',
    appId: '1:932555800316:ios:d1d05d658a5a0a9d886179',
    messagingSenderId: '932555800316',
    projectId: 'firebase-all-features',
    databaseURL: 'https://firebase-all-features-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firebase-all-features.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdKsSmB3dbcrkN5yQi1uJNGtnyn9Egxh8',
    appId: '1:932555800316:ios:d1d05d658a5a0a9d886179',
    messagingSenderId: '932555800316',
    projectId: 'firebase-all-features',
    databaseURL: 'https://firebase-all-features-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firebase-all-features.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRgZOXoE4olEIqx7-BLPsRXgXkeJSq9KE',
    appId: '1:932555800316:web:275310827dae32b8886179',
    messagingSenderId: '932555800316',
    projectId: 'firebase-all-features',
    authDomain: 'fir-all-features-dd471.firebaseapp.com',
    databaseURL: 'https://firebase-all-features-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'firebase-all-features.firebasestorage.app',
  );

}